### ISSUE TITLE
Guide and Author scores are not updated when rating a guide

### ISSUE THREAD

**Issue by amagh** [amagh/Hiker-Guide#1]
Sometimes (usually a new rating) when a user rates a guide, the rating/reviews for the guide and author are not updated.

Firebase throws; 
```
DatabaseError: User code called from the Firebase Database runloop threw an exception:
                                            java.lang.NullPointerException: Attempt to read from field 'int project.hikerguide.models.datamodels.Author.score' on a null object reference
                                                at project.hikerguide.utilities.FirebaseProviderUtils$5.doTransaction(FirebaseProviderUtils.java:519)
                                                at com.google.android.gms.internal.qu.zza(Unknown Source)
                                                at com.google.firebase.database.zzf.run(Unknown Source)
                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                at java.lang.Thread.run(Thread.java:761)
```

However, on subsequent edits of the rating, the guide and author scores are updated correctly.

**Comment by amagh** [comment]
Resolved. See d917d1464c38df21cb9511f02e26989c8f311e65
